Format shell scripts with shfmt

diff --git a/bin/psql-jq b/bin/psql-jq
--- a/bin/psql-jq
+++ b/bin/psql-jq
@@ -5,7 +5,7 @@ set -uo pipefail
 print_usage() {
     local this_script=${0##*/}
 
-    cat << EOF
+    cat <<EOF
 Execute SQL query with \`psql\`, produce pretty-printed JSON output with
 \`jq\`.
 
@@ -31,36 +31,37 @@ jq_args=()
 
 while :; do
     case ${1:-} in
-        -\?|--help)
-            print_usage
-            exit
-            ;;
-        -C|--color-output|-M|--monochrome-output)
-            jq_args+=("$1")
-            ;;
-        -c|--command)
-            if [[ -n ${2:-} ]]; then
-                command=$2
-                shift
-            else
-                printf 'ERROR: "--command" requires a non-empty argument.\n' >&2
-                exit 1
-            fi
-            ;;
-        --)
+    -\? | --help)
+        print_usage
+        exit
+        ;;
+    -C | --color-output | -M | --monochrome-output)
+        jq_args+=("$1")
+        ;;
+    -c | --command)
+        if [[ -n ${2:-} ]]; then
+            command=$2
             shift
-            break
-            ;;
-        -?*)
-            psql_args+=("$1")
+        else
+            printf 'ERROR: "--command" requires a non-empty argument.\n' >&2
+            exit 1
+        fi
+        ;;
+    --)
+        shift
+        break
+        ;;
+    -?*)
+        psql_args+=("$1")
 
-            if [[ -n ${2:-} && $2 != -* ]]; then
-                psql_args+=("$2")
-                shift
-            fi
-            ;;
-        *)
-            break
+        if [[ -n ${2:-} && $2 != -* ]]; then
+            psql_args+=("$2")
+            shift
+        fi
+        ;;
+    *)
+        break
+        ;;
     esac
 
     shift
@@ -77,7 +78,7 @@ if [[ ${#jq_args[@]} -eq 0 && -t 1 ]]; then
     jq_args+=(-C)
 fi
 
-psql -q -t ${psql_args[@]:+"${psql_args[@]}"} << EOF
+psql -q -t ${psql_args[@]:+"${psql_args[@]}"} <<EOF
 \\o '|jq ${jq_args[@]:+"${jq_args[@]}"} .'
 select row_to_json(t) from ($command) t
 EOF
