Format shell scripts with shfmt

diff --git a/bin/tools-update b/bin/tools-update
--- a/bin/tools-update
+++ b/bin/tools-update
@@ -28,7 +28,7 @@ do_update() {
     local update_status=0
     $cmd || update_status=$?
 
-    if (( update_status != 0 && update_status != ERROR_UPDATE_COMMAND_NOT_FOUND )); then
+    if ((update_status != 0 && update_status != ERROR_UPDATE_COMMAND_NOT_FOUND)); then
         local error_status="Failed to update: $tool (exit_status=$update_status)"
         echo -e "\\n$error_status" >&2
         script_error_statuses+=("$error_status")
@@ -36,7 +36,10 @@ do_update() {
 }
 
 do_update_git_project() {
-    cmd_exist git || { echo "Skip, because \`git\` command not found" >&2; return "$ERROR_UPDATE_COMMAND_NOT_FOUND"; }
+    cmd_exist git || {
+        echo "Skip, because \`git\` command not found" >&2
+        return "$ERROR_UPDATE_COMMAND_NOT_FOUND"
+    }
 
     local path=$1
 
@@ -58,7 +61,7 @@ do_update_git_project() {
 
         git pull --ff-only origin master || git_pull_status=$?
 
-        if (( git_pull_status != 0 )); then
+        if ((git_pull_status != 0)); then
             exit "$git_pull_status"
         fi
 
@@ -72,6 +75,7 @@ update_dotfiles() {
 
 update_emacsd() {
     local path=~/.emacs.d
+
     do_update_git_project "$path" && (
         cd "$path"
         make compile
@@ -80,36 +84,52 @@ update_emacsd() {
 }
 
 update_npm() {
-    cmd_exist npm || { echo "Skip, because \`npm\` command not found" >&2; return "$ERROR_UPDATE_COMMAND_NOT_FOUND"; }
+    cmd_exist npm || {
+        echo "Skip, because \`npm\` command not found" >&2
+        return "$ERROR_UPDATE_COMMAND_NOT_FOUND"
+    }
+
     npm update --location=global --ignore-scripts
 }
 
 update_rubygems() {
-    cmd_exist gem || { echo "Skip, because \`gem\` command not found" >&2; return "$ERROR_UPDATE_COMMAND_NOT_FOUND"; }
+    cmd_exist gem || {
+        echo "Skip, because \`gem\` command not found" >&2
+        return "$ERROR_UPDATE_COMMAND_NOT_FOUND"
+    }
+
     gem update --system && gem update && gem clean --silent
 }
 
 update_brew() {
-    cmd_exist brew || { echo "Skip, because \`brew\` command not found" >&2; return "$ERROR_UPDATE_COMMAND_NOT_FOUND"; }
-    brew update && \
-        brew bundle install --global && \
-        brew upgrade && \
-        brew cleanup --scrub
+    cmd_exist brew || {
+        echo "Skip, because \`brew\` command not found" >&2
+        return "$ERROR_UPDATE_COMMAND_NOT_FOUND"
+    }
+
+    brew update \
+        && brew bundle install --global \
+        && brew upgrade \
+        && brew cleanup --scrub
 }
 
 update_rustup() {
-    cmd_exist rustup || { echo "Skip, because \`rustup\` command not found" >&2; return "$ERROR_UPDATE_COMMAND_NOT_FOUND"; }
+    cmd_exist rustup || {
+        echo "Skip, because \`rustup\` command not found" >&2
+        return "$ERROR_UPDATE_COMMAND_NOT_FOUND"
+    }
+
     rustup update
 }
 
-do_update "dotfiles"       update_dotfiles 1
-do_update ".emacs.d"       update_emacsd
-do_update "npm"            update_npm
-do_update "RubyGems"       update_rubygems
+do_update "dotfiles" update_dotfiles 1
+do_update ".emacs.d" update_emacsd
+do_update "npm" update_npm
+do_update "RubyGems" update_rubygems
 do_update "Rust toolchain" update_rustup
-do_update "Homebrew"       update_brew
+do_update "Homebrew" update_brew
 
-if (( ${#script_error_statuses[@]} > 0 )); then
+if ((${#script_error_statuses[@]} > 0)); then
     echo -en "\\n=== Failures summary ===\\n\\n" >&2
 
     for error_status in "${script_error_statuses[@]}"; do
