bash, brew: replace pnpm with npm

diff --git a/bin/tools-update b/bin/tools-update
--- a/bin/tools-update
+++ b/bin/tools-update
@@ -92,16 +92,16 @@ update_emacsd() {
     )
 }
 
-update_pnpm() {
-    (cmd_exist pnpm && cmd_exist jq) || {
-        echo "Skip, because \`pnpm\` or \`jq\` commands not found" >&2
+update_npm() {
+    (cmd_exist npm && cmd_exist jq) || {
+        echo "Skip, because \`npm\` or \`jq\` commands not found" >&2
         return "$ERROR_UPDATE_COMMAND_NOT_FOUND"
     }
 
     jq --raw-output0 '.dependencies | keys[]' ~/Projects/dotfiles/global-package.json \
-        | xargs -0 pnpm --global add
+        | xargs -0 npm --global install
 
-    pnpm update --global
+    npm update --global
 }
 
 update_rubygems() {
@@ -136,7 +136,7 @@ update_rustup() {
 
 do_update "dotfiles" update_dotfiles 1
 do_update ".emacs.d" update_emacsd
-do_update "pnpm" update_pnpm
+do_update "npm" update_npm
 do_update "RubyGems" update_rubygems
 do_update "Rust toolchain" update_rustup
 do_update "Homebrew" update_brew
